# Copyright (c) 2021 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3.6'

services:

  ia_emb_subscriber:
    depends_on:
      - ia_common
    build:
      context: $PWD/../tools/EmbSubscriber
      dockerfile: $PWD/../tools/EmbSubscriber/Dockerfile
      args:
        EII_VERSION: ${EII_VERSION}
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}
        UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
        CMAKE_INSTALL_PREFIX: ${EII_INSTALL_PATH}
    image: ${DOCKER_REGISTRY}ia_emb_subscriber:${EII_VERSION}
    container_name: ia_emb_subscriber
    hostname: ia_emb_subscriber
    network_mode: host
    user: ${EII_UID}
    environment:
      AppName: "EmbSubscriber"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${eii_no_proxy},${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      ETCD_PREFIX: ${ETCD_PREFIX}
      CertType: "zmq"
    volumes:
      - "vol_eii_socket:${SOCKET_DIR}"
    secrets:
      - ca_etcd
      - etcd_EmbSubscriber_cert
      - etcd_EmbSubscriber_key

secrets:
  etcd_EmbSubscriber_cert:
    file: provision/Certificates/EmbSubscriber/EmbSubscriber_client_certificate.pem
  etcd_EmbSubscriber_key:
    file: provision/Certificates/EmbSubscriber/EmbSubscriber_client_key.pem
