version: '3.6'

services:

  emb_publisher:
    depends_on:
      - ia_eiibase
      - ia_common
      - ia_zmq_broker
    build:
      context: $PWD/../tools/EmbPublisher
      dockerfile: $PWD/../tools/EmbPublisher/Dockerfile
      args:
        EII_VERSION: ${EII_VERSION}
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}
        UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
        CMAKE_INSTALL_PREFIX: ${EII_INSTALL_PATH}
    image: ${DOCKER_REGISTRY}emb_publisher:${EII_VERSION}
    container_name: emb_publisher
    hostname: emb_publisher
    network_mode: host
    user: ${EII_UID}
    environment:
      AppName: "EmbPublisher"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${eii_no_proxy},${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      ETCD_PREFIX: ${ETCD_PREFIX}
      CertType: "zmq"
    volumes:
      - "vol_eii_socket:${SOCKET_DIR}"
    secrets:
      - ca_etcd
      - etcd_EmbPublisher_cert
      - etcd_EmbPublisher_key

secrets:
  etcd_EmbPublisher_cert:
    file: provision/Certificates/EmbPublisher/EmbPublisher_client_certificate.pem
  etcd_EmbPublisher_key:
    file: provision/Certificates/EmbPublisher/EmbPublisher_client_key.pem
