version: '3.6'

services:

  emb_publisher:
    depends_on:
      - ia_eiibase
      - ia_common
      - ia_zmq_broker
    build:
      context: $PWD/../tools/EmbPublisher
      dockerfile: $PWD/../tools/EmbPublisher/Dockerfile
      args:
        EII_VERSION: ${EII_VERSION}
        EII_UID: ${EII_UID}
        EII_USER_NAME: ${EII_USER_NAME}
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}
        UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
        CMAKE_INSTALL_PREFIX: ${EII_INSTALL_PATH}
    image: ${DOCKER_REGISTRY}emb_publisher:${EII_VERSION}
    container_name: emb_publisher
    hostname: emb_publisher
    environment:
      AppName: "EmbPublisher"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      ETCD_PREFIX: ${ETCD_PREFIX}
    networks:
      - eii
    volumes:
      - "vol_eii_socket:${SOCKET_DIR}"
      - ./Certificates/EmbPublisher:/run/secrets/EmbPublisher:ro
      - ./Certificates/rootca/cacert.pem:/run/secrets/rootca/cacert.pem:ro
